import { Actions } from '@pagopa/selfcare-common-frontend/lib/utils/constants';
import {
  InstitutionTypeEnum,
  ProductOnBoardingStatusEnum,
} from '../../api/generated/b4f-dashboard/OnboardedProductResource';
import { Party } from '../../model/Party';

export const mockedParties: Array<Party> = [
  {
    description: 'Comune di Bari',
    urlLogo: 'image',
    partyId: '1',
    digitalAddress: 'comune.bari@pec.it',
    fiscalCode: '111111111111',
    category: 'Comuni e loro Consorzi e Associazioni',
    registeredOffice: 'Piazza della Scala, 2',
    zipCode: '20121',
    typology: 'Pubblica Amministrazione',
    externalId: 'externalId1',
    originId: 'originId1',
    origin: 'IPA',
    institutionType: 'PA',
    recipientCode: 'CGDAS23A',
    geographicTaxonomies: [],
    supportEmail: '',
    products: [
      {
        productId: 'prod-pagopa',
        authorized: true,
        productOnBoardingStatus: ProductOnBoardingStatusEnum.ACTIVE,
        userRole: 'ADMIN',
        billing: {
          vatNumber: '81001510528',
          recipientCode: 'FLGKROWP',
          publicServices: true,
        },
        userProductActions: [Actions.AccessProductBackoffice, Actions.ListAvailableProducts],
        institutionType: InstitutionTypeEnum.PA,
        origin: 'IVASS',
        originId: '20128',
      },
      {
        productId: 'prod-pn',
        authorized: true,
        productOnBoardingStatus: ProductOnBoardingStatusEnum.ACTIVE,
        userRole: 'ADMIN',
        billing: {
          vatNumber: '66554328912',
          recipientCode: 'cccc',
          publicServices: true,
        },
        userProductActions: [
          Actions.ListActiveProducts,
          Actions.AccessProductBackoffice,
          Actions.ViewBilling,
        ],
        institutionType: InstitutionTypeEnum.GPU,
        origin: 'IVASS',
        originId: '20128',
      },
    ],
    delegation: false,
    status: undefined,
    userRole: undefined,
  },
  {
    description: 'Comune di Milano',
    urlLogo: 'image',
    partyId: '2',
    digitalAddress: 'comune.milano@pec.it',
    fiscalCode: 'fiscalCodeMilano',
    category: 'Comuni e loro Consorzi e Associazioni',
    registeredOffice: 'Piazza della Scala, 2',
    zipCode: '20121',
    typology: 'Pubblica Amministrazione',
    externalId: 'externalId2',
    originId: 'originId2',
    origin: 'IPA',
    institutionType: 'PA',
    recipientCode: 'CGDAS23B',
    geographicTaxonomies: [], // Use case with no taxonomies
    vatNumber: '81001510528',
    products: [
      {
        productId: 'prod-io',
        authorized: true,
        productOnBoardingStatus: ProductOnBoardingStatusEnum.ACTIVE,
        userRole: 'ADMIN',
        billing: {
          vatNumber: '2222',
          recipientCode: 'cccc',
          publicServices: true,
        },
        userProductActions: [
          Actions.ListActiveProducts,
          Actions.ListAvailableProducts,
          Actions.ManageProductGroups,
          Actions.ListProductUsers,
          Actions.CreateProductUsers,
          Actions.UpdateProductUsers,
          Actions.DeleteProductUsers,
          Actions.AccessProductBackoffice,
          Actions.ViewDelegations,
          Actions.ViewBilling,
        ],
        institutionType: InstitutionTypeEnum.GPU,
        origin: 'IVASS',
        originId: '20128',
      },
    ],
    delegation: false,
    status: undefined,
    userRole: undefined,
  },
  {
    description: 'Comune di Roma',
    urlLogo: 'image',
    partyId: '3',
    digitalAddress: 'comune.roma@pec.it',
    fiscalCode: 'fiscalCodeRoma',
    category: 'Comuni e loro Consorzi e Associazioni',
    registeredOffice: 'Piazza della Scala, 2',
    zipCode: '20121',
    typology: 'Pubblica Amministrazione',
    externalId: 'externalId3',
    originId: 'originId3',
    origin: 'IPA',
    institutionType: 'PSP',
    recipientCode: 'CGDAS23C',
    geographicTaxonomies: [
      // Use case with two taxonomies
      { code: '058091', desc: 'Roma - Comune' },
      { code: '015146', desc: 'Milano - Comune' },
    ],
    vatNumber: '111122211111',
    city: 'Roma',
    country: 'IT',
    products: [
      // Use case with one delegable product
      {
        productId: 'prod-io',
        authorized: true,
        productOnBoardingStatus: ProductOnBoardingStatusEnum.ACTIVE,
        userRole: 'ADMIN',
        billing: {
          vatNumber: '11111111111',
          recipientCode: 'CH435V',
          publicServices: true,
        },
        userProductActions: [
          Actions.AccessProductBackoffice,
          Actions.CreateProductUsers,
          Actions.UpdateProductUsers,
          Actions.DeleteProductUsers,
          Actions.ListProductUsers,
          Actions.ListProductGroups,
          Actions.ManageProductGroups,
          Actions.ViewDelegations,
          Actions.ViewBilling,
          Actions.ListAvailableProducts,
          Actions.CreateDelegation,
          Actions.ViewContract,
        ],
        institutionType: 'PA',
        origin: 'IVASS',
        originId: '20128',
      },
      {
        productId: 'prod-pagopa',
        authorized: false,
        productOnBoardingStatus: ProductOnBoardingStatusEnum.ACTIVE,
        userRole: 'ADMIN',
        billing: {
          vatNumber: '11111111111',
          recipientCode: 'CH435V',
          publicServices: true,
        },
        userProductActions: [
          Actions.ListActiveProducts,
          Actions.ListAvailableProducts,
          Actions.ManageProductGroups,
          Actions.CreateProductUsers,
          Actions.UpdateProductUsers,
          Actions.DeleteProductUsers,
          Actions.ListProductUsers,
          Actions.AccessProductBackoffice,
          Actions.ViewDelegations,
          Actions.ViewBilling,
          Actions.ViewContract,
          Actions.UploadLogo,
        ],
        institutionType: 'PSP',
        origin: 'IVASS',
        originId: '20128',
      },
      {
        productId: 'prod-dashboard-psp',
        authorized: false,
        productOnBoardingStatus: ProductOnBoardingStatusEnum.ACTIVE,
        userRole: 'ADMIN',
        billing: {
          vatNumber: '11111111111',
          recipientCode: 'CH435V',
          publicServices: true,
        },
        userProductActions: [
          Actions.ListActiveProducts,
          Actions.ListAvailableProducts,
          Actions.ManageProductGroups,
          Actions.CreateProductUsers,
          Actions.UpdateProductUsers,
          Actions.DeleteProductUsers,
          Actions.ListProductUsers,
          Actions.AccessProductBackoffice,
          Actions.ViewDelegations,
          Actions.ViewBilling,
          Actions.CreateDelegation,
        ],
        institutionType: 'GPU',
        origin: 'IVASS',
        originId: '20128',
      },
      {
        productId: 'prod-io-premium',
        authorized: false,
        productOnBoardingStatus: ProductOnBoardingStatusEnum.ACTIVE,
        userRole: 'ADMIN',
        billing: {
          vatNumber: '11111111111',
          recipientCode: 'CH435V',
          publicServices: true,
        },
        userProductActions: [
          Actions.ListActiveProducts,
          Actions.ListAvailableProducts,
          Actions.ManageProductGroups,
          Actions.ListProductUsers,
          Actions.AccessProductBackoffice,
        ],
        institutionType: 'PA',
        origin: 'IVASS',
        originId: '20128',
      },
      // Use case with prod-interop and prod-interop-coll
      {
        productId: 'prod-interop',
        authorized: true,
        productOnBoardingStatus: ProductOnBoardingStatusEnum.ACTIVE,
        userRole: 'ADMIN',
        billing: {
          vatNumber: '3395867495',
          recipientCode: 'NBG455B',
          publicServices: true,
        },
        userProductActions: [
          Actions.AccessProductBackoffice,
          Actions.CreateProductUsers,
          Actions.UpdateProductUsers,
          Actions.DeleteProductUsers,
          Actions.ListProductUsers,
          Actions.ViewContract,
        ],
        institutionType: 'GPU',
        origin: 'IVASS',
        originId: '20128',
      },
      {
        productId: 'prod-interop-coll',
        authorized: true,
        productOnBoardingStatus: ProductOnBoardingStatusEnum.ACTIVE,
        userRole: 'ADMIN',
        billing: {
          vatNumber: '3395867495',
          recipientCode: 'NBG455B',
          publicServices: true,
        },
        userProductActions: [
          Actions.AccessProductBackoffice,
          Actions.CreateProductUsers,
          Actions.UpdateProductUsers,
          Actions.DeleteProductUsers,
          Actions.ListProductUsers,
        ],
        institutionType: 'GPU',
        origin: 'IVASS',
        originId: '20128',
      },
      {
        productId: 'prod-interop-atst',
        authorized: true,
        productOnBoardingStatus: ProductOnBoardingStatusEnum.REJECTED,
        userRole: 'ADMIN',
        billing: {
          vatNumber: '3395867495',
          recipientCode: 'NBG455B',
          publicServices: true,
        },
        userProductActions: [
          Actions.AccessProductBackoffice,
          Actions.CreateProductUsers,
          Actions.UpdateProductUsers,
          Actions.DeleteProductUsers,
          Actions.ListProductUsers,
        ],
        institutionType: 'GPU',
        origin: 'IVASS',
        originId: '20128',
      },
      {
        productId: 'prod-pn',
        productOnBoardingStatus: ProductOnBoardingStatusEnum.ACTIVE,
        userRole: 'ADMIN',
        billing: {
          vatNumber: '3395867495',
          recipientCode: 'NBG455B',
          publicServices: true,
        },
        userProductActions: [
          Actions.AccessProductBackoffice,
          Actions.CreateProductUsers,
          Actions.UpdateProductUsers,
          Actions.DeleteProductUsers,
          Actions.ListProductUsers,
          Actions.ManageProductGroups,
          Actions.ViewDelegations,
          Actions.ViewBilling,
          Actions.ViewContract,
        ],
        institutionType: 'GPU',
        origin: 'IVASS',
        originId: '20128',
      },
      {
        productId: 'prod-pn-dev',
        authorized: true,
        productOnBoardingStatus: ProductOnBoardingStatusEnum.ACTIVE,
        userRole: 'ADMIN',
        billing: {
          vatNumber: '3395867495',
          recipientCode: 'NBG455B',
          publicServices: true,
        },
        institutionType: 'GPU',
        origin: 'IVASS',
        originId: '20128',
      },
    ],
    delegation: false,
    status: 'ACTIVE',
    userRole: 'ADMIN',
  },
];
