const IS_DEVELOP = import.meta.env.DEV;
const IS_TEST = import.meta.env.TEST;

export const MOCK_USER = IS_DEVELOP;
export const LOG_REDUX_ACTIONS = IS_DEVELOP && !IS_TEST;

export const LOADING_RETRIEVE_ONBOARDING_REQUEST = 'RETRIEVE_ONBOARDING_REQUEST';
export const LOADING_RETRIEVE_INSTITUTIONS = 'RETRIEVE_INSTITUTIONS';
export const LOADING_TASK_TOKEN_EXCHANGE = 'TOKEN_EXCHANGE';
export const LOADING_TASK_PRODUCTS = 'LOADING_TASK_PRODUCTS';

export const STATUSES_ALLOWED_TO_SEE_REQUESTS = [
  'COMPLETED',
  'ACTIVE',
  'PENDING',
  'REJECTED',
  'TOBEVALIDATED',
];
